import { summarizeChecks, EMPTY_CI } from "./checks.ts";
import { PROBE_MARKER_PATH, SCRATCH_DIR, type CiSummary, type GhStatus, type PrInfo, type PrStatus } from "./types.ts";

export const PROBE_SCRIPT_PATH = `${SCRATCH_DIR}/probe.sh`;
export const PROBE_COMMAND = `sh ${PROBE_SCRIPT_PATH}`;

/**
 * POSIX sh probe written into the workspace and executed through a workspace
 * terminal (`sh .pi-web/github-pr/probe.sh`). It writes one file per fact so
 * the browser never has to parse shell-generated JSON, and the probe marker
 * (probe.json) is written last. Contains no single quotes and no user input.
 */
export const PROBE_SCRIPT = `#!/bin/sh
# Generated by @gtrabanco/pi-web-github-pr-status. Do not edit.
D=${SCRATCH_DIR}
mkdir -p "$D"
T=$(date +%s 2>/dev/null)
if [ -z "$T" ]; then T=0; fi
G=1
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  git rev-parse --abbrev-ref HEAD >"$D/branch.txt" 2>/dev/null
  git rev-parse HEAD >"$D/head.txt" 2>/dev/null
  git rev-parse --abbrev-ref --symbolic-full-name "@{u}" >"$D/upstream.txt" 2>/dev/null
  git diff --cached --numstat 2>/dev/null | wc -l | tr -d " " >"$D/staged.txt"
  git diff --numstat 2>/dev/null | wc -l | tr -d " " >"$D/unstaged.txt"
  git ls-files --others --exclude-standard --exclude=.pi-web/github-pr/ 2>/dev/null | wc -l | tr -d " " >"$D/untracked.txt"
  git rev-list --left-right --count "@{u}"..."HEAD" >"$D/ab.txt" 2>/dev/null
  if command -v gh >/dev/null 2>&1; then
    GH_PAGER=cat gh pr view --json number,url,title,state,isDraft,author,headRefName,baseRefName,mergeable,mergeStateStatus,reviewDecision,statusCheckRollup >"$D/pr.json" 2>"$D/gh.err"
  else
    printf "gh: command not found" >"$D/gh.err"
  fi
else
  G=0
fi
printf '{"v":1,"ts":%s,"git":%s}\n' "$T" "$G" >"$D/probe.json"
exit 0
`;

/** Raw contents of the probe scratch files (missing files are undefined). */
export interface ProbeFiles {
  probe?: string;
  branch?: string;
  head?: string;
  upstream?: string;
  staged?: string;
  unstaged?: string;
  untracked?: string;
  aheadBehind?: string;
  pr?: string;
  ghErr?: string;
}

function parseCount(raw: string | undefined): number {
  if (raw === undefined) return 0;
  const match = /^\s*(\d+)\s*$/.exec(raw);
  return match === null ? 0 : Number(match[1]);
}

function parseAheadBehind(raw: string | undefined): { ahead: number; behind: number } {
  if (raw === undefined) return { ahead: 0, behind: 0 };
  const parts = raw.trim().split("\t");
  const behind = parseCount(parts[0]);
  const ahead = parseCount(parts[1]);
  return { ahead, behind };
}

function parseMarker(raw: string | undefined): { git: boolean; probeAt?: number; usable: boolean } {
  if (raw === undefined || raw.trim() === "") return { git: false, usable: false };
  try {
    const parsed: unknown = JSON.parse(raw);
    if (typeof parsed !== "object" || parsed === null) return { git: false, usable: false };
    const record = parsed as Record<string, unknown>;
    return {
      git: record.git === 1 || record.git === true,
      probeAt: typeof record.ts === "number" && Number.isFinite(record.ts) ? record.ts : undefined,
      usable: true,
    };
  } catch {
    return { git: false, usable: false };
  }
}

const GH_MISSING_PATTERN = /command not found|not recognized/iu;
const GH_AUTH_PATTERN = /gh auth login|GH_TOKEN|authentication/iu;
const GH_NO_PR_PATTERN = /no pull requests found/iu;

function classifyGh(ghErr: string | undefined, hasPr: boolean): { gh?: GhStatus; ghMessage?: string } {
  if (hasPr) return { gh: "ok" };
  const message = ghErr?.trim();
  if (message === undefined || message === "") return { gh: "error", ghMessage: "gh output unavailable" };
  if (GH_MISSING_PATTERN.test(message)) return { gh: "missing", ghMessage: message.split("\n")[0] };
  if (GH_AUTH_PATTERN.test(message)) return { gh: "unauthenticated", ghMessage: message.split("\n")[0] };
  if (GH_NO_PR_PATTERN.test(message)) return { gh: "ok" };
  return { gh: "error", ghMessage: message.split("\n")[0] };
}

function optionalString(value: unknown): string | undefined {
  return typeof value === "string" && value.trim() !== "" ? value.trim() : undefined;
}

function parseBoolean(value: unknown): boolean {
  return value === true || value === "true";
}

/** Validate and narrow an untrusted `gh pr view` JSON object. */
export function parsePrJson(raw: string | undefined): PrInfo | undefined {
  if (raw === undefined || raw.trim() === "") return undefined;
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return undefined;
  }
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) return undefined;
  const record = parsed as Record<string, unknown>;
  const number = record.number;
  if (typeof number !== "number" || !Number.isInteger(number) || number < 1 || number > 2_147_483_647) return undefined;
  const url = record.url;
  if (typeof url !== "string" || !/^https:\/\/[\w.-]+/u.test(url)) return undefined;
  const state = record.state;
  if (state !== "OPEN" && state !== "CLOSED" && state !== "MERGED") return undefined;
  const author = record.author;
  return {
    number,
    url,
    title: typeof record.title === "string" ? record.title : "",
    state,
    isDraft: parseBoolean(record.isDraft),
    author: typeof author === "object" && author !== null ? optionalString((author as Record<string, unknown>).login) : undefined,
    headRefName: optionalString(record.headRefName),
    baseRefName: optionalString(record.baseRefName),
    mergeable: optionalString(record.mergeable),
    mergeStateStatus: optionalString(record.mergeStateStatus),
    reviewDecision: optionalString(record.reviewDecision),
  };
}

const EMPTY_STATUS: PrStatus = Object.freeze({
  git: false,
  staged: 0,
  unstaged: 0,
  untracked: 0,
  ahead: 0,
  behind: 0,
  hasUpstream: false,
  ci: EMPTY_CI,
  cold: true,
});

/** Build the workspace status from probe scratch file contents. */
export function parseProbeResult(files: ProbeFiles): PrStatus {
  const marker = parseMarker(files.probe);
  if (!marker.usable) return { ...EMPTY_STATUS };
  if (!marker.git) {
    return {
      ...EMPTY_STATUS,
      git: false,
      cold: false,
      probeAt: marker.probeAt,
    };
  }

  const upstream = optionalString(files.upstream);
  const counts = parseAheadBehind(files.aheadBehind);
  const pr = parsePrJson(files.pr);
  const gh = classifyGh(files.ghErr, pr !== undefined);
  const staged = parseCount(files.staged);
  const unstaged = parseCount(files.unstaged);
  const untracked = parseCount(files.untracked);
  const ahead = upstream === undefined ? 0 : counts.ahead;
  const behind = upstream === undefined ? 0 : counts.behind;

  const ci: CiSummary = pr !== undefined && pr.state === "OPEN" ? summarizeChecks(extractRollup(files.pr)) : EMPTY_CI;
  return {
    git: true,
    cold: false,
    probeAt: marker.probeAt,
    branch: optionalString(files.branch),
    head: optionalString(files.head),
    upstream,
    staged,
    unstaged,
    untracked,
    ahead,
    behind,
    hasUpstream: upstream !== undefined,
    pr,
    ci,
    gh: gh.gh,
    ghMessage: gh.ghMessage,
    isDirty: staged + unstaged + untracked > 0,
    unpushed: upstream === undefined || ahead > 0,
  };
}

function extractRollup(prRaw: string | undefined): unknown {
  if (prRaw === undefined) return undefined;
  try {
    const parsed: unknown = JSON.parse(prRaw);
    if (typeof parsed === "object" && parsed !== null && !Array.isArray(parsed)) {
      return (parsed as Record<string, unknown>).statusCheckRollup;
    }
  } catch {
    /* already reported as missing pr */
  }
  return undefined;
}

export const PROBE_MARKER = PROBE_MARKER_PATH;

/** Read one scratch file, mapping read failures (missing file) to undefined. */
export async function readProbeFile(readFile: (path: string) => Promise<{ content: string; binary: boolean }>, path: string): Promise<string | undefined> {
  try {
    const file = await readFile(path);
    return file.binary ? undefined : file.content;
  } catch {
    return undefined;
  }
}

export const PROBE_FILE_PATHS = {
  probe: `${SCRATCH_DIR}/probe.json`,
  branch: `${SCRATCH_DIR}/branch.txt`,
  head: `${SCRATCH_DIR}/head.txt`,
  upstream: `${SCRATCH_DIR}/upstream.txt`,
  staged: `${SCRATCH_DIR}/staged.txt`,
  unstaged: `${SCRATCH_DIR}/unstaged.txt`,
  untracked: `${SCRATCH_DIR}/untracked.txt`,
  aheadBehind: `${SCRATCH_DIR}/ab.txt`,
  pr: `${SCRATCH_DIR}/pr.json`,
  ghErr: `${SCRATCH_DIR}/gh.err`,
} as const;

/**
 * Build an in-memory `readFile` over fixture contents, mirroring how the
 * browser-side cache reads scratch files by path: existing-but-empty files
 * resolve to "", unknown paths reject like a missing file.
 */
export function probeFileReader(files: ProbeFiles): (path: string) => Promise<{ content: string; binary: boolean }> {
  const contents = new Map<string, string>();
  for (const [key, path] of Object.entries(PROBE_FILE_PATHS)) {
    const value = (files as Record<string, string | undefined>)[key];
    if (value !== undefined) contents.set(path, value);
  }
  return async (path) => {
    const content = contents.get(path);
    if (content === undefined) throw new Error(`File not found: ${path}`);
    return { content, binary: false };
  };
}

/** Read every probe scratch file, mapping read failures to undefined. */
export async function readAllProbeFiles(readFile: (path: string) => Promise<{ content: string; binary: boolean }>): Promise<ProbeFiles> {
  const paths = Object.values(PROBE_FILE_PATHS) as readonly string[];
  const [probe, branch, head, upstream, staged, unstaged, untracked, aheadBehind, pr, ghErr] = await Promise.all(
    paths.map(async (path) => readProbeFile(readFile, path)),
  );
  return { probe, branch, head, upstream, staged, unstaged, untracked, aheadBehind, pr, ghErr };
}
