import { SCRATCH_DIR } from "./types.ts";
import { watcherFreshWindowMs } from "./schedule.ts";

export const WATCH_SCRIPT_PATH = `${SCRATCH_DIR}/watch.sh`;
export const WATCH_COMMAND = `sh ${WATCH_SCRIPT_PATH}`;
/** One fact-collection cycle and exit: used by tests and manual verification. */
export const WATCH_ONCE_COMMAND = `sh ${WATCH_SCRIPT_PATH} once`;

/** Watcher-owned state and browser-owned control files inside the scratch dir. */
export const WATCHER_STATE_PATH = `${SCRATCH_DIR}/watcher.json`;
export const INTERVAL_PATH = `${SCRATCH_DIR}/interval.txt`;
export const TRIGGER_PATH = `${SCRATCH_DIR}/trigger`;
export const STOP_PATH = `${SCRATCH_DIR}/stop`;

/** Hard self-termination age so an orphaned watcher cannot run forever. */
export const WATCHER_MAX_LIFETIME_S = 43_200;
const WATCHER_STATE_FILE = `${SCRATCH_DIR}/watcher.json`;

/**
 * POSIX sh watcher written into the workspace and executed through a single
 * long-lived workspace terminal (`sh .pi-web/github-pr/watch.sh`). Every cycle
 * writes the same fact files the old per-probe script did, so the browser
 * never runs a terminal per refresh — pi-web keeps every command-run terminal
 * forever (jmfederico/pi-web#225), so terminal count must stay at one.
 *
 * Self-termination: exits (and removes watcher.json) when the browser-owned
 * `stop` file appears, when the browser-owned interval.txt drops to 0, or
 * after WATCHER_MAX_LIFETIME_S. `trigger` forces an immediate cycle (manual
 * refresh). No single quotes beyond JSON literals and no user input.
 */
export const WATCH_SCRIPT = `#!/bin/sh
# Generated by @gtrabanco/pi-web-github-pr-status. Do not edit.
D=${SCRATCH_DIR}
S=${WATCHER_STATE_FILE}
I=${INTERVAL_PATH}
T=${TRIGGER_PATH}
P=${STOP_PATH}
mkdir -p "$D"

cycle() {
  N=$(date +%s 2>/dev/null)
  if [ -z "$N" ]; then N=0; fi
  G=1
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    git rev-parse --abbrev-ref HEAD >"$D/branch.txt" 2>/dev/null
    git rev-parse HEAD >"$D/head.txt" 2>/dev/null
    git rev-parse --abbrev-ref --symbolic-full-name "@{u}" >"$D/upstream.txt" 2>/dev/null
    git diff --cached --numstat 2>/dev/null | wc -l | tr -d " " >"$D/staged.txt"
    git diff --numstat 2>/dev/null | wc -l | tr -d " " >"$D/unstaged.txt"
    git ls-files --others --exclude-standard --exclude=.pi-web/github-pr/ 2>/dev/null | wc -l | tr -d " " >"$D/untracked.txt"
    git rev-list --left-right --count "@{u}"..."HEAD" >"$D/ab.txt" 2>/dev/null
    if command -v gh >/dev/null 2>&1; then
      if command -v timeout >/dev/null 2>&1; then
        GH_PAGER=cat timeout 20 gh pr view --json number,url,title,state,isDraft,author,headRefName,baseRefName,mergeable,mergeStateStatus,reviewDecision,statusCheckRollup >"$D/pr.json" 2>"$D/gh.err"
      else
        GH_PAGER=cat gh pr view --json number,url,title,state,isDraft,author,headRefName,baseRefName,mergeable,mergeStateStatus,reviewDecision,statusCheckRollup >"$D/pr.json" 2>"$D/gh.err"
      fi
    else
      printf "gh: command not found" >"$D/gh.err"
    fi
  else
    G=0
  fi
  printf '{"v":1,"ts":%s,"git":%s}\\n' "$N" "$G" >"$D/probe.json"
}

state() {
  W=$(date +%s 2>/dev/null)
  if [ -z "$W" ]; then W=0; fi
  printf '{"v":1,"pid":%s,"ts":%s,"interval":%s}\\n' "$$" "$W" "$IV"
}

if [ "$1" = "once" ]; then
  IV=0
  cycle
  exit 0
fi

T0=$(date +%s 2>/dev/null)
if [ -z "$T0" ]; then T0=0; fi
while :; do
  if [ -f "$P" ]; then rm -f "$S"; exit 0; fi
  N=$(date +%s 2>/dev/null)
  if [ -z "$N" ]; then N=0; fi
  if [ $((N - T0)) -ge ${WATCHER_MAX_LIFETIME_S} ]; then rm -f "$S"; exit 0; fi
  IV=$(cat "$I" 2>/dev/null)
  case "$IV" in ""|*[!0-9]*) IV=90 ;; esac
  if [ "$IV" -le 0 ]; then rm -f "$S"; rm -f "$T"; exit 0; fi
  state >"$S"
  cycle
  REM=$IV
  while [ "$REM" -gt 0 ]; do
    if [ -f "$T" ]; then rm -f "$T"; break; fi
    if [ -f "$P" ]; then break; fi
    SL=2
    if [ "$REM" -lt 2 ]; then SL=$REM; fi
    sleep "$SL"
    REM=$((REM - SL))
  done
done
`;

/** Parsed watcher.json record; missing fields mean "unknown". */
export interface WatcherState {
  pid?: number;
  ts?: number;
  interval?: number;
}

/** Validate and narrow an untrusted watcher.json file. */
export function parseWatcherState(raw: string | undefined): WatcherState {
  if (raw === undefined || raw.trim() === "") return {};
  try {
    const parsed: unknown = JSON.parse(raw);
    if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) return {};
    const record = parsed as Record<string, unknown>;
    return {
      pid: typeof record.pid === "number" && Number.isFinite(record.pid) ? record.pid : undefined,
      ts: typeof record.ts === "number" && Number.isFinite(record.ts) ? record.ts : undefined,
      interval: typeof record.interval === "number" && Number.isFinite(record.interval) && record.interval >= 0 ? record.interval : undefined,
    };
  } catch {
    return {};
  }
}

/**
 * True when the watcher touched its state file recently enough, judged
 * against its own reported cycle interval (falling back to the configured
 * one) so slow cycles are not misread as a dead watcher.
 */
export function isWatcherAlive(state: WatcherState, settingsIntervalSec: number, nowSec: number): boolean {
  if (state.ts === undefined) return false;
  const intervalSec = state.interval !== undefined && state.interval > 0 ? state.interval : settingsIntervalSec;
  const windowMs = watcherFreshWindowMs(intervalSec * 1000);
  return nowSec * 1000 - state.ts * 1000 <= windowMs;
}

/** Body of the browser-owned interval file consumed by the watcher script. */
export function serializeInterval(seconds: number): string {
  return `${String(Math.max(0, Math.floor(seconds)))}\n`;
}
